options:
  loglevel:
    default: 1
    type: int
    description: Mon and OSD debug level. Max is 20.
  source:
    type: string
    default:
    description: |
      Optional configuration to support use of additional sources such as:
        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main
      The last option should be used in conjunction with the key configuration
      option.
      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise but is provided in the Ubuntu cloud archive.
  key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
  use-syslog:
    type: boolean
    default: False
    description: |
      If set to True, supporting services will log to syslog.
  ceph-public-network:
    type: string
    default:
    description: |
      The IP address and netmask of the public (front-side) network (e.g.,
      192.168.0.0/24).
      If multiple networks are to be used, a space-delimited list of a.b.c.d/x
      can be provided.
  prefer-ipv6:
    type: boolean
    default: False
    description: |
      If True enables IPv6 support. The charm will expect network interfaces
      to be configured with an IPv6 address. If set to False (default) IPv4
      is expected.

      NOTE: these charms do not currently support IPv6 privacy extension. In
      order for this charm to function correctly, the privacy extension must be
      disabled and a non-temporary address must be configured/available on
      your network interface.
  fs-name:
    type: string
    default: 
    description: The name to use when creating the pool for the filesystem
  pool-type:
    type: string
    default: replicated
    description: Type of pool to use, replicated or erasure
  pool-weight:
    type: int
    default: 10
    description: |
      The percentage (0-100) of the cluster data on this pool is 
      expected to consume. This is used to scale the number of pgs in the pool. 
      For example, a single pool as the only use of a ceph cluster would be set to 100. 
      If two filesystems share a Ceph cluster with equal expected data, set to 50.
  erasure-profile:
    type: string
    default: "default"
    description: |
      The name of the erasure profile to use, this only applies if the pool-type
      is set to erasure. Settingn this to a custom value enables setting several
      of the erasure configuration parameters.
  erasure-plugin:
    type: string
    default: "jerasure"
    description: |
      The erasure plugin to use. This only applies if the pool-type is set to 
      erasure and the erasure-profile is not 'default'
  erasure-failure-domain:
    type: string
    default: "osd"
    description: |
      The erasure failure domain. This only applies if the pool-type is set to
      erasure and the erasure-profile is not 'default'
  erasure-k:
    type: int
    default: 3
    description: |
      The number of erasure data chunks. This only applies if the pool-type is 
      set to erasure and the erasure-profile is not 'default'
  erasure-m:
    type: int
    default: 2
    description: |
      The number of encoding chunks. This only applies if the pool-type is set 
      to erasure and the erasure-profile is not 'default'
  erasure-l:
    type: int
    default: 3
    description: |
      The locality setting for erasure encoding. This only applies if the pool-type
      is set to erasure, the erasure-profile is not 'default', and the erasure-plugin
      supports a locality setting.
  compression-mode:
    type: string
    default:
    description: Compression mode to use for the pool
  compression-algorithm:
    type: string
    default: 'snappy'
    description: Compression algorithm
  compression-required-ratio:
    type: float
    default: .50
    description: The required ration for compression to be used
